// Generated by CoffeeScript 1.9.1
(function() {
  var ER,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ER = exports;

  ER.FunCSSError = (function(superClass) {
    extend(FunCSSError, superClass);

    function FunCSSError(message) {
      this.message = message;
      this.stack = this.message + "\n" + (new Error()).stack;
    }

    FunCSSError.prototype.setup = function(message) {
      this.message = message;
      return this.stack = this.message + "\n" + (new Error()).stack;
    };

    return FunCSSError;

  })(Error);

  ER.TypeError = (function(superClass) {
    extend(TypeError, superClass);

    function TypeError() {
      return TypeError.__super__.constructor.apply(this, arguments);
    }

    return TypeError;

  })(ER.FunCSSError);

  ER.SyntaxError = (function(superClass) {
    extend(SyntaxError, superClass);

    function SyntaxError() {
      return SyntaxError.__super__.constructor.apply(this, arguments);
    }

    return SyntaxError;

  })(ER.FunCSSError);

  ER.UnknownAtRule = (function(superClass) {
    extend(UnknownAtRule, superClass);

    function UnknownAtRule(name) {
      this.name = name;
      this.setup("Unknown at rule: " + this.name);
    }

    return UnknownAtRule;

  })(ER.FunCSSError);

  ER.BlockRequired = (function(superClass) {
    extend(BlockRequired, superClass);

    function BlockRequired(name) {
      this.name = name;
      this.setup("Block required for " + this.name);
    }

    return BlockRequired;

  })(ER.SyntaxError);

  ER.BlockRequired = (function(superClass) {
    extend(BlockRequired, superClass);

    function BlockRequired(name) {
      this.name = name;
      this.setup("Block not allowed for " + this.name);
    }

    return BlockRequired;

  })(ER.SyntaxError);

  ER.TypeInferenceNotImplemented = (function(superClass) {
    extend(TypeInferenceNotImplemented, superClass);

    function TypeInferenceNotImplemented(definable) {
      this.definable = definable;
      this.setup("Automatic type inference is not yet implemented. Please provide an explicit type for " + this.definable);
    }

    return TypeInferenceNotImplemented;

  })(ER.TypeError);

  ER.NotImplemented = (function(superClass) {
    extend(NotImplemented, superClass);

    function NotImplemented(message) {
      this.message = message;
      this.setup(this.message);
    }

    return NotImplemented;

  })(ER.TypeError);

  ER.UnknownAtRule = (function(superClass) {
    extend(UnknownAtRule, superClass);

    function UnknownAtRule(atRuleName) {
      this.atRuleName = atRuleName;
      this.setup("Unknown at-rule: " + this.atRuleName);
    }

    return UnknownAtRule;

  })(ER.SyntaxError);

  ER.UnknownProperty = (function(superClass) {
    extend(UnknownProperty, superClass);

    function UnknownProperty(propertyName) {
      this.propertyName = propertyName;
      this.setup("Unknown property: " + this.propertyName);
    }

    return UnknownProperty;

  })(ER.TypeError);

  ER.UnknownType = (function(superClass) {
    extend(UnknownType, superClass);

    function UnknownType(typeName) {
      this.typeName = typeName;
      this.setup("Unknown type: " + this.typeName);
    }

    return UnknownType;

  })(ER.TypeError);

  ER.DecodingNotSupported = (function(superClass) {
    extend(DecodingNotSupported, superClass);

    function DecodingNotSupported(type) {
      this.type = type;
      this.setup("Decoding from JS is not supported for type " + this.type);
    }

    return DecodingNotSupported;

  })(ER.TypeError);

  ER.InvalidColor = (function(superClass) {
    extend(InvalidColor, superClass);

    function InvalidColor(color) {
      this.color = color;
      this.setup("Invalid color: " + this.color);
    }

    return InvalidColor;

  })(ER.TypeError);

  ER.IncludeFileNotFound = (function(superClass) {
    extend(IncludeFileNotFound, superClass);

    function IncludeFileNotFound(fileName) {
      this.fileName = fileName;
      this.setup("Include file not found: " + this.fileName);
    }

    return IncludeFileNotFound;

  })(ER.TypeError);

}).call(this);
