// Generated by CoffeeScript 1.9.1
(function() {
  var ER,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ER = exports;

  ER.FunCSSError = (function(superClass) {
    extend(FunCSSError, superClass);

    function FunCSSError(message) {
      this.message = message;
      this.stack = (new Error()).stack;
    }

    return FunCSSError;

  })(Error);

  ER.TypeError = (function(superClass) {
    extend(TypeError, superClass);

    function TypeError() {
      return TypeError.__super__.constructor.apply(this, arguments);
    }

    return TypeError;

  })(ER.FunCSSError);

  ER.SyntaxError = (function(superClass) {
    extend(SyntaxError, superClass);

    function SyntaxError() {
      return SyntaxError.__super__.constructor.apply(this, arguments);
    }

    return SyntaxError;

  })(ER.FunCSSError);

  ER.UnknownAtRule = (function(superClass) {
    extend(UnknownAtRule, superClass);

    function UnknownAtRule(name) {
      this.name = name;
      UnknownAtRule.__super__.constructor.call(this, "Unknown at rule: " + this.name);
    }

    return UnknownAtRule;

  })(ER.FunCSSError);

  ER.BlockRequired = (function(superClass) {
    extend(BlockRequired, superClass);

    function BlockRequired(name) {
      this.name = name;
      BlockRequired.__super__.constructor.call(this, "Block required for " + this.name);
    }

    return BlockRequired;

  })(ER.SyntaxError);

  ER.TypeInferenceNotImplemented = (function(superClass) {
    extend(TypeInferenceNotImplemented, superClass);

    function TypeInferenceNotImplemented(definable) {
      this.definable = definable;
      TypeInferenceNotImplemented.__super__.constructor.call(this, "Automatic type inference is not yet implemented. Please provide an explicit type for " + this.definable);
    }

    return TypeInferenceNotImplemented;

  })(ER.TypeError);

  ER.UnknownAtRule = (function(superClass) {
    extend(UnknownAtRule, superClass);

    function UnknownAtRule(name) {
      this.name = name;
      UnknownAtRule.__super__.constructor.call(this, "Unknown at-rule: " + this.name);
    }

    return UnknownAtRule;

  })(ER.SyntaxError);

  ER.UnknownProperty = (function(superClass) {
    extend(UnknownProperty, superClass);

    function UnknownProperty(name) {
      this.name = name;
      UnknownProperty.__super__.constructor.call(this, "Unknown property: " + this.name);
    }

    return UnknownProperty;

  })(ER.TypeError);

  ER.UnknownType = (function(superClass) {
    extend(UnknownType, superClass);

    function UnknownType(name) {
      this.name = name;
      UnknownType.__super__.constructor.call(this, "Unknown type: " + this.name);
    }

    return UnknownType;

  })(ER.TypeError);

}).call(this);
