// Generated by CoffeeScript 1.9.1
(function() {
  var FunCSS, fs;

  FunCSS = require("../compiler");

  fs = require("fs");

  exports.run = function() {
    var content;
    content = fs.readFileSync(process.argv[2]).toString("utf-8");
    return FunCSS.compile(content, {
      done: function(err, result) {
        if (err) {
          return console.error(err.stack);
        } else {
          return console.log(result);
        }
      }
    });
  };

}).call(this);
