// Generated by CoffeeScript 1.9.1
(function() {
  var FunCSS, fs;

  FunCSS = require("../compiler");

  fs = require("fs");

  exports.run = function() {
    var content, result;
    content = fs.readFileSync(process.argv[2]).toString("utf-8");
    result = FunCSS.compile(content);
    return console.log(result);
  };

}).call(this);
