// Generated by CoffeeScript 1.9.1
(function() {
  var FunCSS, content, fs, result;

  FunCSS = require("../compiler");

  fs = require("fs");

  content = fs.readFileSync(process.argv[2]).toString("utf-8");

  result = FunCSS.compile(content);

  console.log(result);

}).call(this);
