// Generated by CoffeeScript 1.9.1
(function() {
  var Generator, Semantics, Syntax;

  Syntax = require("./syntax");

  Semantics = require("./semantics");

  Generator = require("./generator");

  exports.compile = function(str, options) {
    var b, browserify, fs, ig, js, path, s, ss, stream;
    if (options == null) {
      options = {};
    }
    ss = Syntax(str, options);
    fs = Semantics(ss, options);
    ig = Generator(fs, options);
    js = ig.toString();
    if (options.browserify !== false) {
      browserify = require("browserify");
      stream = require("stream");
      path = require("path");
      s = new stream.Readable();
      s._read = function() {};
      s.push(js);
      s.push(null);
      b = browserify(s, {
        basedir: ".",
        paths: [path.join(__dirname, "../../rtlib")]
      });
      return b.bundle(function(err, buf) {
        return console.log(buf.toString("utf-8"));
      });
    } else {
      return js;
    }
  };

}).call(this);
