// Generated by CoffeeScript 1.9.1
(function() {
  var Beautifier, Generator, Semantics, Syntax, assert;

  assert = require("./helpers/assert");

  Syntax = require("./syntax");

  Semantics = require("./semantics");

  Generator = require("./generator");

  Beautifier = require("./beautifier");

  console.debug = null;

  exports.compile = function(str, options) {
    var b, browserify, e, fs, ig, js, path, s, ss, stream;
    if (options == null) {
      options = {};
    }
    assert.hasProp({
      options: options
    }, "done");
    try {
      ss = Syntax(str, options);
      fs = Semantics(ss, options);
      ig = Generator(fs, options);
      js = ig.toString();
    } catch (_error) {
      e = _error;
      options.done(e);
      return;
    }
    if (options.browserify !== false) {
      browserify = require("browserify");
      stream = require("stream");
      path = require("path");
      s = new stream.Readable();
      s._read = function() {};
      s.push(js);
      s.push(null);
      b = browserify(s, {
        basedir: ".",
        paths: [path.join(__dirname, "../../rtlib")]
      });
      return b.bundle(function(err, buf) {
        if (err) {
          return options.done(err);
        } else {
          return Beautifier(buf.toString("utf-8"), options);
        }
      });
    } else {
      return Beautifier(js, options);
    }
  };

}).call(this);
