// Generated by CoffeeScript 1.9.2
(function() {
  var Cascade, Def, SG, SS, Semantics, k, ref, v;

  SS = require("./syntax/ss_nodes");

  SG = require("./semantics/sg_nodes");

  Cascade = require("./semantics/cascade");

  Def = require("./semantics/def");

  module.exports = Semantics = function(ss) {
    var i, len, ref, rule, sg;
    sg = new SG.SemanticGraph;
    ref = ss.value;
    for (i = 0, len = ref.length; i < len; i++) {
      rule = ref[i];
      if (rule instanceof SS.QualifiedRule) {
        Cascade.qualifiedRule(rule, sg);
      } else if (rule instanceof SS.AtRule) {
        Semantics.atRules[rule.name].handle(rule, sg);
      } else {
        throw new Error("Internal error in Semantics: Unknown rule type in SS.Stylesheet");
      }
    }
    return sg;
  };

  ref = {
    atRules: {
      def: Def.def
    }
  };
  for (k in ref) {
    v = ref[k];
    Semantics[k] = v;
  }

}).call(this);
