// Generated by CoffeeScript 1.9.1
(function() {
  var DM, GR, VL, assert;

  assert = "../../../helpers/assert";

  GR = require("../../../syntax/gr_nodes");

  VL = require("../../values/vl_nodes");

  DM = exports;

  DM.Metric = (function() {
    function Metric(name, canonicalUnitName, units) {
      this.name = name;
      this.canonicalUnitName = canonicalUnitName;
      this.units = units != null ? units : {};
      this.units[this.canonicalUnitName] = new VL.Number(1);
    }

    Metric.prototype.grammar = function() {
      var g, metric;
      metric = this;
      g = new GR.Dimension(this.name, function(x) {
        var multiplier, ref;
        if (x.value === 0) {
          return new VL.Dimension(new VL.Number(0), metric.canonicalUnitName);
        }
        multiplier = (ref = metric.units[x.unit]) != null ? ref : this.stream.noMatchCurrent(metric.name);
        return new VL.Dimension(new VL.Multiply(new VL.Number(x.value), multiplier), metric.canonicalUnitName);
      });
      g.decodejs = (function(_this) {
        return function(x) {
          return x + "+" + (JSON.stringify(_this.canonicalUnitName));
        };
      })(this);
      return g;
    };

    return Metric;

  })();

}).call(this);
