// Generated by CoffeeScript 1.9.1
(function() {
  var IG, remove_empty_stylesheets, walk;

  walk = require("../helpers/walk");

  IG = require("./ig_nodes");

  remove_empty_stylesheets = walk(function() {
    if (this instanceof IG.InsertStylesheet) {
      if (!this.value.value.length) {
        return {
          remove: true
        };
      } else {
        return {
          skip: true
        };
      }
    }
  });

}).call(this);
