// Generated by CoffeeScript 1.9.1
(function() {
  var UglifyJS;

  UglifyJS = require("uglify-js");

  module.exports = function(js, options) {
    var e, result;
    try {
      result = UglifyJS.minify(js, {
        fromString: true,
        mangle: false,
        compress: {
          sequences: false,
          properties: true,
          dead_code: true,
          drop_debugger: false,
          unsafe: false,
          conditionals: true,
          comparisons: true,
          evaluate: true,
          booleans: true,
          loops: true,
          unused: true,
          hoist_funs: true,
          hoist_vars: false,
          if_return: true,
          join_vars: true,
          cascade: true,
          side_effects: true,
          warnings: true,
          global_defs: {}
        },
        output: {
          beautify: true,
          indent_start: 0,
          indent_level: 2,
          quote_keys: false,
          space_colon: true,
          ascii_only: true,
          inline_script: true,
          source_map: null,
          width: 80,
          max_line_len: 32000,
          bracketize: true,
          comments: false,
          semicolons: true,
          quote_style: 0
        }
      });
    } catch (_error) {
      e = _error;
      console.error(js);
      options.done(e);
      return;
    }
    return options.done(null, result.code);
  };

}).call(this);
