// Generated by CoffeeScript 1.9.2
(function() {
  var Colon, DF, Definable, DefinableWithType, Definition, Equals, Parser, SS, Snd, TP, VariableDefinition, VariableName;

  TP = require("../values/tp_nodes");

  Parser = require("../../syntax/parser");

  SS = require("../../syntax/ss_nodes");

  DF = require("./df_nodes");

  Snd = function(_, y) {
    return y;
  };

  Colon = new TP.DelimLike(new SS.ColonToken);

  Equals = new TP.DelimLike(new SS.DelimToken("="));

  VariableName = new TP.Ident(function(x) {
    return new DF.VariableName(x.value);
  });

  Definable = VariableName;

  DefinableWithType = new TP.Juxtaposition(Definable, new TP.Juxtaposition(Colon, new TP.Ident, Snd), function(variableName, typeName) {
    return [variableName, typeName];
  });

  VariableDefinition = new TP.Juxtaposition(DefinableWithType, new TP.Juxtaposition(Equals, new TP.RawTokens(), Snd), function(arg, rawValue) {
    var pattern, typeName;
    pattern = arg[0], typeName = arg[1];
    return new DF.Definition(pattern, typeName, rawValue);
  });

  Definition = VariableDefinition;

  module.exports = Definition;

}).call(this);
