// Generated by CoffeeScript 1.9.2
(function() {
  var Definable, Definition, VariableName,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  exports.Definable = Definable = (function() {
    function Definable() {}

    return Definable;

  })();

  exports.VariableName = VariableName = (function(superClass) {
    extend(VariableName, superClass);

    function VariableName(value) {
      this.value = value;
    }

    return VariableName;

  })(Definable);

  exports.Definition = Definition = (function() {
    function Definition(definable, type, rawValue) {
      this.definable = definable;
      this.type = type;
      this.rawValue = rawValue;
    }

    return Definition;

  })();

}).call(this);
