// Generated by CoffeeScript 1.9.1
(function() {
  var FS, SS, Semantics;

  SS = require("../syntax/ss_nodes");

  FS = require("./fs_nodes");

  module.exports = Semantics = function(ss, options) {
    return new FS.FunctionalStylesheet(ss, options);
  };

}).call(this);
