// Generated by CoffeeScript 1.9.2
(function() {
  var SL, Selector, SelectorGroup, TP, TypeSelector;

  TP = require("./values/tp_nodes");

  SL = require("./selectors/sl_nodes");

  TypeSelector = new TP.Ident(function(x) {
    return new SL.TypeSelector(x.value);
  });

  Selector = TypeSelector;

  SelectorGroup = new TP.DelimitedByComma(Selector);

  module.exports = SelectorGroup;

}).call(this);
