// Generated by CoffeeScript 1.9.2
(function() {
  var CS, SemanticGraph, Vds;

  CS = require("./cascade/cs_nodes");

  Vds = require("./values/vds");

  exports.SemanticGraph = SemanticGraph = (function() {
    function SemanticGraph() {
      this.simpleRules = [];
      this.propertyValueTypes = {};
      this.types = Vds.TYPES;
    }

    SemanticGraph.prototype.getType = function(name) {
      return this.types[name];
    };

    SemanticGraph.prototype.getQuotedType = function(name) {
      return this.propertyValueTypes[name];
    };

    return SemanticGraph;

  })();

}).call(this);
