// Generated by CoffeeScript 1.9.2
(function() {
  var Generator, Semantics, Syntax;

  Syntax = require("./compiler/syntax");

  Semantics = require("./compiler/semantics");

  Generator = require("./compiler/generator");

  exports.compile = function(str) {
    var js, sg, ss;
    ss = Syntax(str);
    sg = Semantics(ss);
    js = Generator(sg);
    return js.toString();
  };

}).call(this);
