// Generated by CoffeeScript 1.9.2
(function() {
  exports.present = function(values) {
    var name, results, value;
    results = [];
    for (name in values) {
      value = values[name];
      if (value == null) {
        throw new Error(name + " must be present");
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

  exports.hasProp = function(values, property) {
    var name, results, value;
    results = [];
    for (name in values) {
      value = values[name];
      if (value == null) {
        throw new Error(name + " must be present");
      }
      if (value[property] == null) {
        throw new Error(name + " must have property " + property);
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

}).call(this);
