// Generated by CoffeeScript 1.9.2
(function() {
  var SS, Stream;

  SS = require("../syntax/ss_nodes");

  Stream = (function() {
    function Stream(items) {
      var t;
      (this.items = (function() {
        var i, len, results;
        results = [];
        for (i = 0, len = items.length; i < len; i++) {
          t = items[i];
          results.push(t);
        }
        return results;
      })()).push(new SS.EOFToken);
      this.position = 0;
    }

    Stream.prototype.consume_next = function() {
      return this.current = this.items[this.position++];
    };

    Stream.prototype.next = function() {
      return this.items[this.position];
    };

    Stream.prototype.reconsume_current = function() {
      return this.items.unshift(this.current);
    };

    return Stream;

  })();

  module.exports = Stream;

}).call(this);
