// Generated by CoffeeScript 1.9.2
(function() {
  var SimpleRule;

  exports.SimpleRule = SimpleRule = (function() {
    function SimpleRule(opts) {
      this.mediaQuery = opts.mediaQuery, this.selector = opts.selector, this.name = opts.name, this.value = opts.value, this.important = opts.important;
    }

    SimpleRule.prototype.isConstantMediaQuery = function() {
      return false;
    };

    SimpleRule.prototype.isConstantValue = function() {
      return false;
    };

    SimpleRule.prototype.isConstantSelector = function() {
      return false;
    };

    SimpleRule.prototype.selectorSpecificity = function() {
      return [0, 0, 0];
    };

    return SimpleRule;

  })();

}).call(this);
