// Generated by CoffeeScript 1.9.1
(function() {
  var Parser;

  Parser = require(".././syntax/parser");

  module.exports = function(input) {
    return Parser.parse_stylesheet(input);
  };

}).call(this);
