// Generated by CoffeeScript 1.9.1
(function() {
  var GR, SL, Selector, SelectorGroup, TypeSelector;

  GR = require("../../syntax/gr_nodes");

  SL = require("./sl_nodes");

  TypeSelector = new GR.Ident(function(x) {
    return new SL.TypeSelector(x.value);
  });

  Selector = TypeSelector;

  SelectorGroup = new GR.DelimitedByComma(Selector);

  module.exports = SelectorGroup;

}).call(this);
